import type { Metadata } from "next";
import '@/ui/styles/globals.scss';
import { Header, Main, SiteHeading } from '@/ui/components';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const navigation = [
	{ url: '/overview', label: 'Översikt', isActive: false },
	{ url: '/finances', label: 'Ekonomi', isActive: false },
	{ url: '#', label: 'Detaljer', isActive: false },
];

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Header navigation={navigation} />
				<Main>
					<SiteHeading />
					{children}
				</Main>
			</body>
		</html>
	);
}







