import type { Metadata } from "next";
import '@/ui/styles/globals.scss';
import styles from './layout.module.scss';
import classNames from 'classnames';
import { Header, Main, SiteHeading } from '@/ui/components';
import ToastProvider from '@/ui/components/1-atoms/Toast/Toast';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const navigation = [
	{ url: '/overview', label: 'Översikt', isActive: false },
	{ url: '/finances', label: 'Ekonomi', isActive: false },
	{ url: '#', label: 'Detaljer', isActive: false },
];

export const revalidate = 10;

export default function RootLayout({
	modal,
	children,
}: Readonly<{
	modal: React.ReactNode;
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={classNames(styles.layout)}>
				<ToastProvider>
					<Header navigation={navigation} />
					<Main>
						<SiteHeading />
						{children}
					</Main>
					<div className={classNames(styles.layout_modal)}>{modal}</div>
				</ToastProvider>
			</body>
		</html>
	);
}







